In [25]:
import torch
import torch.nn as nn

In [26]:
torch.manual_seed(1)
input_layer = 3
output_layer = 4
weights = nn.Parameter(torch.randn(input_layer, output_layer))
weights.shape, weights

(torch.Size([3, 4]),
 Parameter containing:
 tensor([[ 0.6614,  0.2669,  0.0617,  0.6213],
         [-0.4519, -0.1661, -1.5228,  0.3817],
         [-1.0276, -0.5631, -0.8923, -0.0583]], requires_grad=True))

In [27]:
input_x = torch.tensor([3., 3., 4.])

dot_product = input_x @ weights
dot_product.shape, dot_product

(torch.Size([4]),
 tensor([-3.4821, -1.9498, -7.9524,  2.7760], grad_fn=<SqueezeBackward4>))

In [28]:
torch.manual_seed(1)
bias = nn.Parameter(torch.randn(1, output_layer))
bias.shape, bias

(torch.Size([1, 4]),
 Parameter containing:
 tensor([[0.6614, 0.2669, 0.0617, 0.6213]], requires_grad=True))

In [29]:
z = dot_product + bias

In [30]:
z

tensor([[-2.8207, -1.6829, -7.8908,  3.3973]], grad_fn=<AddBackward0>)

In [34]:
a = torch.tensor([1.])
b = torch.tensor([[1.]])

a.shape, b.shape, (a + b).shape

(torch.Size([1]), torch.Size([1, 1]), torch.Size([1, 1]))